import type {
  Alert,
  EarlyWarning,
  KpiStat,
  Project,
  RiskTrendPoint,
  StateRiskDatum,
} from './types';
import { riskBandFromScore } from './risk';

export const projects: Project[] = [
  {
    id: 'PRJ-001',
    name: 'Mumbai Coastal Road Phase II',
    code: 'MCR-II',
    ministry: 'Ministry of Road Transport & Highways',
    agency: 'NHAI / MCGM',
    state: 'Maharashtra',
    district: 'Mumbai',
    sector: 'Transport',
    status: 'at-risk',
    riskScore: 68,
    riskBand: 'high',
    budgetCrore: 14200,
    spentCrore: 7180,
    progressPercent: 42,
    visualProgressEstimate: 35,
    cctvAvailable: true,
    startDate: '2023-04-12',
    targetEndDate: '2026-03-30',
    contractor: 'L&T Construction',
    evidence: ['observed', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-23T09:14:00Z',
  },
  {
    id: 'PRJ-002',
    name: 'Ken-Betwa River Interlinking',
    code: 'KBRL-01',
    ministry: 'Ministry of Jal Shakti',
    agency: 'NWDA',
    state: 'Madhya Pradesh',
    district: 'Tikamgarh',
    sector: 'Water Resources',
    status: 'delayed',
    riskScore: 81,
    riskBand: 'critical',
    budgetCrore: 18050,
    spentCrore: 5240,
    progressPercent: 28,
    visualProgressEstimate: 16,
    cctvAvailable: true,
    startDate: '2022-11-02',
    targetEndDate: '2025-12-15',
    contractor: 'Afcons Infrastructure',
    evidence: ['reported', 'observed', 'ai-interpreted', 'verified'],
    lastUpdated: '2026-08-24T03:42:00Z',
  },
  {
    id: 'PRJ-003',
    name: 'Delhi-Mumbai Industrial Corridor Node',
    code: 'DMIC-ND',
    ministry: 'Ministry of Commerce & Industry',
    agency: 'NICDC',
    state: 'Gujarat',
    district: 'Ahmedabad',
    sector: 'Industrial',
    status: 'on-track',
    riskScore: 24,
    riskBand: 'low',
    budgetCrore: 9600,
    spentCrore: 3120,
    progressPercent: 61,
    visualProgressEstimate: 60,
    cctvAvailable: true,
    startDate: '2023-01-20',
    targetEndDate: '2027-06-30',
    contractor: 'Tata Projects',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-22T14:05:00Z',
  },
  {
    id: 'PRJ-004',
    name: 'Bengaluru Suburban Rail Project',
    code: 'BSRP-02',
    ministry: 'Ministry of Railways',
    agency: 'K-RIDE',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    sector: 'Railways',
    status: 'at-risk',
    riskScore: 57,
    riskBand: 'high',
    budgetCrore: 15765,
    spentCrore: 6890,
    progressPercent: 38,
    visualProgressEstimate: 33,
    cctvAvailable: false,
    startDate: '2022-06-15',
    targetEndDate: '2026-09-30',
    contractor: 'IRCON International',
    evidence: ['reported', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-23T19:30:00Z',
  },
  {
    id: 'PRJ-005',
    name: 'Kutch Green Hydrogen Hub',
    code: 'KGHH-01',
    ministry: 'Ministry of New & Renewable Energy',
    agency: 'NGEL',
    state: 'Gujarat',
    district: 'Kutch',
    sector: 'Energy',
    status: 'on-track',
    riskScore: 18,
    riskBand: 'low',
    budgetCrore: 19300,
    spentCrore: 4210,
    progressPercent: 33,
    visualProgressEstimate: 33,
    cctvAvailable: true,
    startDate: '2024-02-10',
    targetEndDate: '2028-04-30',
    contractor: 'NTPC Green Energy',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-21T11:18:00Z',
  },
  {
    id: 'PRJ-006',
    name: 'Brahmaputra Flood Embankment Upgrade',
    code: 'BFEU-03',
    ministry: 'Ministry of Jal Shakti',
    agency: 'WRD Assam',
    state: 'Assam',
    district: 'Dibrugarh',
    sector: 'Water Resources',
    status: 'critical',
    riskScore: 89,
    riskBand: 'critical',
    budgetCrore: 4200,
    spentCrore: 2980,
    progressPercent: 46,
    visualProgressEstimate: 29,
    cctvAvailable: false,
    startDate: '2022-03-01',
    targetEndDate: '2025-08-30',
    contractor: 'Nepa Bridge & Infrastructure',
    evidence: ['reported', 'observed', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-24T06:55:00Z',
  },
  {
    id: 'PRJ-007',
    name: 'Chennai Outer Ring Road Phase III',
    code: 'CORR-III',
    ministry: 'Ministry of Road Transport & Highways',
    agency: 'TNRDC',
    state: 'Tamil Nadu',
    district: 'Chennai',
    sector: 'Transport',
    status: 'on-track',
    riskScore: 33,
    riskBand: 'moderate',
    budgetCrore: 6750,
    spentCrore: 2310,
    progressPercent: 47,
    visualProgressEstimate: 45,
    cctvAvailable: true,
    startDate: '2023-09-05',
    targetEndDate: '2026-12-15',
    contractor: 'GMR Infrastructure',
    evidence: ['observed', 'ai-interpreted'],
    lastUpdated: '2026-08-20T08:00:00Z',
  },
  {
    id: 'PRJ-008',
    name: 'Teesta Stage IV Hydropower Project',
    code: 'TST-IV',
    ministry: 'Ministry of Power',
    agency: 'NHPC Limited',
    state: 'Sikkim',
    district: 'North Sikkim',
    sector: 'Energy',
    status: 'delayed',
    riskScore: 64,
    riskBand: 'high',
    budgetCrore: 8900,
    spentCrore: 5170,
    progressPercent: 52,
    visualProgressEstimate: 47,
    cctvAvailable: true,
    startDate: '2021-10-12',
    targetEndDate: '2026-02-28',
    contractor: 'NHPC Limited',
    evidence: ['reported', 'observed', 'predicted'],
    lastUpdated: '2026-08-22T22:10:00Z',
  },
  {
    id: 'PRJ-009',
    name: 'Visakhapatnam Smart City Phase II',
    code: 'VSC-II',
    ministry: 'Ministry of Housing & Urban Affairs',
    agency: 'GVMC',
    state: 'Andhra Pradesh',
    district: 'Visakhapatnam',
    sector: 'Urban',
    status: 'on-track',
    riskScore: 29,
    riskBand: 'low',
    budgetCrore: 5400,
    spentCrore: 1980,
    progressPercent: 54,
    visualProgressEstimate: 53,
    cctvAvailable: true,
    startDate: '2023-07-01',
    targetEndDate: '2027-01-15',
    contractor: 'Shapoorji Pallonji',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-19T15:45:00Z',
  },
  {
    id: 'PRJ-010',
    name: 'Indore Metro Line Corridor',
    code: 'IMLC-01',
    ministry: 'Ministry of Housing & Urban Affairs',
    agency: 'MPMRCL',
    state: 'Madhya Pradesh',
    district: 'Indore',
    sector: 'Urban',
    status: 'at-risk',
    riskScore: 49,
    riskBand: 'moderate',
    budgetCrore: 12200,
    spentCrore: 4760,
    progressPercent: 41,
    visualProgressEstimate: 39,
    cctvAvailable: true,
    startDate: '2023-03-18',
    targetEndDate: '2026-11-30',
    contractor: 'Kalpataru Projects',
    evidence: ['reported', 'ai-interpreted'],
    lastUpdated: '2026-08-23T07:22:00Z',
  },
  {
    id: 'PRJ-011',
    name: 'Kolkata East-West Metro Extension',
    code: 'KEMW-EX',
    ministry: 'Ministry of Railways',
    agency: 'KMRCL',
    state: 'West Bengal',
    district: 'Kolkata',
    sector: 'Railways',
    status: 'delayed',
    riskScore: 73,
    riskBand: 'high',
    budgetCrore: 16750,
    spentCrore: 9870,
    progressPercent: 36,
    visualProgressEstimate: 27,
    cctvAvailable: true,
    startDate: '2021-08-22',
    targetEndDate: '2026-05-30',
    contractor: 'Afcons Infrastructure',
    evidence: ['reported', 'observed', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-24T01:12:00Z',
  },
  {
    id: 'PRJ-012',
    name: 'Jaipur-Ajmer Expressway Widening',
    code: 'JAE-WID',
    ministry: 'Ministry of Road Transport & Highways',
    agency: 'NHAI',
    state: 'Rajasthan',
    district: 'Jaipur',
    sector: 'Transport',
    status: 'completed',
    riskScore: 12,
    riskBand: 'low',
    budgetCrore: 3400,
    spentCrore: 3310,
    progressPercent: 100,
    visualProgressEstimate: 100,
    cctvAvailable: true,
    startDate: '2022-05-10',
    targetEndDate: '2026-07-30',
    contractor: 'Dilip Buildcon',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-01T10:00:00Z',
  },
  {
    id: 'PRJ-013',
    name: 'Western Dedicated Freight Corridor (Rewari-Palanpur)',
    code: 'WDFC-04',
    ministry: 'Ministry of Railways',
    agency: 'DFCCIL',
    state: 'Rajasthan',
    district: 'Alwar',
    sector: 'Railways',
    status: 'on-track',
    riskScore: 22,
    riskBand: 'low',
    budgetCrore: 21800,
    spentCrore: 16200,
    progressPercent: 78,
    visualProgressEstimate: 76,
    cctvAvailable: true,
    startDate: '2021-02-15',
    targetEndDate: '2026-10-31',
    contractor: 'L&T Transportation Infra',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-23T11:45:00Z',
  },
  {
    id: 'PRJ-014',
    name: 'Polavaram Headworks Irrigation Dam',
    code: 'PIDW-02',
    ministry: 'Ministry of Jal Shakti',
    agency: 'Polavaram Project Authority',
    state: 'Andhra Pradesh',
    district: 'Eluru',
    sector: 'Water Resources',
    status: 'critical',
    riskScore: 84,
    riskBand: 'critical',
    budgetCrore: 29500,
    spentCrore: 14800,
    progressPercent: 53,
    visualProgressEstimate: 39,
    cctvAvailable: false,
    startDate: '2020-08-01',
    targetEndDate: '2025-11-30',
    contractor: 'Megha Engineering (MEIL)',
    evidence: ['reported', 'observed', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-24T04:10:00Z',
  },
  {
    id: 'PRJ-015',
    name: 'Zojila Strategic All-Weather Tunnel',
    code: 'ZTSH-01',
    ministry: 'Ministry of Road Transport & Highways',
    agency: 'NHIDCL',
    state: 'Jammu & Kashmir',
    district: 'Ganderbal',
    sector: 'Transport',
    status: 'at-risk',
    riskScore: 61,
    riskBand: 'high',
    budgetCrore: 6800,
    spentCrore: 3200,
    progressPercent: 44,
    visualProgressEstimate: 38,
    cctvAvailable: true,
    startDate: '2021-10-15',
    targetEndDate: '2026-12-31',
    contractor: 'Megha Engineering (MEIL)',
    evidence: ['observed', 'predicted', 'ai-interpreted'],
    lastUpdated: '2026-08-23T16:20:00Z',
  },
  {
    id: 'PRJ-016',
    name: 'Gorakhpur Haryana Anu Vidyut Pariyojana',
    code: 'GHNP-01',
    ministry: 'Ministry of Power',
    agency: 'NPCIL',
    state: 'Haryana',
    district: 'Fatehabad',
    sector: 'Energy',
    status: 'on-track',
    riskScore: 27,
    riskBand: 'low',
    budgetCrore: 20594,
    spentCrore: 9350,
    progressPercent: 62,
    visualProgressEstimate: 61,
    cctvAvailable: true,
    startDate: '2021-04-10',
    targetEndDate: '2027-03-31',
    contractor: 'BHEL - L&T Consortium',
    evidence: ['observed', 'verified'],
    lastUpdated: '2026-08-22T09:30:00Z',
  },
];

export const kpiStats: KpiStat[] = [
  {
    id: 'kpi-projects',
    label: 'Active Projects Monitored',
    value: '248',
    delta: '+6',
    trend: 'up',
    hint: 'vs last quarter',
  },
  {
    id: 'kpi-critical',
    label: 'Critical Risk Projects',
    value: '17',
    delta: '+3',
    trend: 'up',
    hint: 'requires immediate attention',
  },
  {
    id: 'kpi-alerts',
    label: 'Open Alerts',
    value: '63',
    delta: '-12',
    trend: 'down',
    hint: 'resolved in last 24h',
  },
  {
    id: 'kpi-budget',
    label: 'Budget at Risk',
    value: '₹1.42L Cr',
    delta: '+8.4%',
    trend: 'up',
    hint: 'exposure across delayed projects',
  },
];

export const riskTrend: RiskTrendPoint[] = [
  { month: 'Mar', low: 142, moderate: 58, high: 24, critical: 9 },
  { month: 'Apr', low: 138, moderate: 61, high: 27, critical: 11 },
  { month: 'May', low: 135, moderate: 64, high: 29, critical: 12 },
  { month: 'Jun', low: 131, moderate: 66, high: 31, critical: 14 },
  { month: 'Jul', low: 128, moderate: 68, high: 34, critical: 15 },
  { month: 'Aug', low: 126, moderate: 70, high: 35, critical: 17 },
];

export const stateRiskData: StateRiskDatum[] = [
  { state: 'Maharashtra', projects: 34, avgRisk: 41, band: 'moderate' },
  { state: 'Madhya Pradesh', projects: 22, avgRisk: 58, band: 'high' },
  { state: 'Gujarat', projects: 19, avgRisk: 27, band: 'low' },
  { state: 'Karnataka', projects: 28, avgRisk: 49, band: 'moderate' },
  { state: 'Assam', projects: 14, avgRisk: 71, band: 'high' },
  { state: 'Tamil Nadu', projects: 21, avgRisk: 38, band: 'moderate' },
  { state: 'Sikkim', projects: 6, avgRisk: 64, band: 'high' },
  { state: 'Andhra Pradesh', projects: 17, avgRisk: 31, band: 'moderate' },
  { state: 'West Bengal', projects: 23, avgRisk: 67, band: 'high' },
  { state: 'Rajasthan', projects: 18, avgRisk: 22, band: 'low' },
  { state: 'Uttar Pradesh', projects: 31, avgRisk: 44, band: 'moderate' },
  { state: 'Bihar', projects: 15, avgRisk: 53, band: 'moderate' },
].map((d) => ({ ...d, band: riskBandFromScore(d.avgRisk) }));

export const alerts: Alert[] = [
  {
    id: 'ALT-1042',
    projectId: 'PRJ-006',
    projectName: 'Brahmaputra Flood Embankment Upgrade',
    title: 'Embankment breach risk — rising river level',
    description:
      'Predictive model indicates 78% probability of embankment overtopping within 14 days. Observed water level 1.2m above seasonal mean.',
    severity: 'critical',
    status: 'active',
    evidence: ['observed', 'predicted', 'ai-interpreted'],
    createdAt: '2026-08-24T06:55:00Z',
    source: 'Hydrological sensor network',
  },
  {
    id: 'ALT-1041',
    projectId: 'PRJ-002',
    projectName: 'Ken-Betwa River Interlinking',
    title: 'Schedule slippage beyond recovery threshold',
    description:
      'Cumulative delay of 248 days against baseline. Contractor mobilisation below committed levels at three work fronts.',
    severity: 'critical',
    status: 'active',
    evidence: ['reported', 'observed', 'ai-interpreted'],
    createdAt: '2026-08-24T03:42:00Z',
    source: 'Project MIS + field reports',
  },
  {
    id: 'ALT-1039',
    projectId: 'PRJ-011',
    projectName: 'Kolkata East-West Metro Extension',
    title: 'Land acquisition bottleneck at Esplanade',
    description:
      'Pending possession for 0.4km corridor segment. Tunnel boring progress stalled 11 days.',
    severity: 'high',
    status: 'acknowledged',
    evidence: ['reported', 'observed'],
    createdAt: '2026-08-24T01:12:00Z',
    source: 'Field inspection report',
  },
  {
    id: 'ALT-1037',
    projectId: 'PRJ-001',
    projectName: 'Mumbai Coastal Road Phase II',
    title: 'Reinforcement corrosion flagged by AI imagery',
    description:
      'Computer-vision analysis of site imagery detected surface cracking consistent with chloride ingress in 3 segments.',
    severity: 'high',
    status: 'active',
    evidence: ['observed', 'ai-interpreted'],
    createdAt: '2026-08-23T09:14:00Z',
    source: 'AI imagery interpretation',
  },
  {
    id: 'ALT-1035',
    projectId: 'PRJ-004',
    projectName: 'Bengaluru Suburban Rail Project',
    title: 'Cost overrun trending above 18%',
    description:
      'Forecast spend exceeds sanctioned cost by 18.2% at current burn rate. Steel and labour escalation primary drivers.',
    severity: 'high',
    status: 'active',
    evidence: ['predicted', 'ai-interpreted'],
    createdAt: '2026-08-23T19:30:00Z',
    source: 'Financial forecasting model',
  },
  {
    id: 'ALT-1032',
    projectId: 'PRJ-008',
    projectName: 'Teesta Stage IV Hydropower',
    title: 'Geological surprise in head race tunnel',
    description:
      'Unexpected shear zone encountered at chainage 1.8km. Support system revision under review.',
    severity: 'high',
    status: 'acknowledged',
    evidence: ['observed', 'reported'],
    createdAt: '2026-08-22T22:10:00Z',
    source: 'Geological inspection',
  },
  {
    id: 'ALT-1028',
    projectId: 'PRJ-010',
    projectName: 'Indore Metro Line Corridor',
    title: 'Labour availability below plan',
    description:
      'Workforce strength at 64% of planned deployment for the month. Minor schedule impact projected.',
    severity: 'moderate',
    status: 'active',
    evidence: ['reported'],
    createdAt: '2026-08-23T07:22:00Z',
    source: 'Contractor weekly report',
  },
  {
    id: 'ALT-1024',
    projectId: 'PRJ-007',
    projectName: 'Chennai Outer Ring Road Phase III',
    title: 'Material delivery delay — bituminous mix',
    description:
      'Batching plant outage caused 3-day supply gap. Alternative source identified.',
    severity: 'moderate',
    status: 'resolved',
    evidence: ['reported', 'verified'],
    createdAt: '2026-08-20T08:00:00Z',
    source: 'Supply chain log',
  },
  {
    id: 'ALT-1019',
    projectId: 'PRJ-003',
    projectName: 'Delhi-Mumbai Industrial Corridor Node',
    title: 'Environmental clearance renewal due',
    description:
      'Coastal regulation zone permit expires in 45 days. Renewal application filed.',
    severity: 'low',
    status: 'acknowledged',
    evidence: ['reported'],
    createdAt: '2026-08-19T12:00:00Z',
    source: 'Compliance tracker',
  },
];

export const earlyWarnings: EarlyWarning[] = [
  {
    id: 'EW-201',
    projectId: 'PRJ-008',
    projectName: 'Teesta Stage IV Hydropower',
    signal: 'Rainfall anomaly forecast',
    detail:
      'Extended-range met forecast shows 160% of normal rainfall in catchment over next 21 days. Spillway capacity review advised.',
    band: 'high',
    evidence: ['predicted', 'ai-interpreted'],
    detectedAt: '2026-08-24T05:00:00Z',
  },
  {
    id: 'EW-198',
    projectId: 'PRJ-001',
    projectName: 'Mumbai Coastal Road Phase II',
    signal: 'Subsidence pattern detected',
    detail:
      'InSAR displacement time-series shows 4.2mm/yr subsidence along reclaimed stretch, accelerating over last 90 days.',
    band: 'high',
    evidence: ['observed', 'ai-interpreted'],
    detectedAt: '2026-08-23T15:30:00Z',
  },
  {
    id: 'EW-195',
    projectId: 'PRJ-010',
    projectName: 'Indore Metro Line Corridor',
    signal: 'Vendor concentration risk',
    detail:
      '62% of structural steel sourced from a single supplier. AI flags supply continuity exposure if order book shifts.',
    band: 'moderate',
    evidence: ['ai-interpreted'],
    detectedAt: '2026-08-23T07:22:00Z',
  },
  {
    id: 'EW-190',
    projectId: 'PRJ-005',
    projectName: 'Kutch Green Hydrogen Hub',
    signal: 'Grid evacuation capacity shortfall',
    detail:
      'Transmission upgrade lagging generation commissioning by ~3 months per inter-connector availability model.',
    band: 'moderate',
    evidence: ['predicted'],
    detectedAt: '2026-08-21T11:18:00Z',
  },
  {
    id: 'EW-187',
    projectId: 'PRJ-009',
    projectName: 'Visakhapatnam Smart City Phase II',
    signal: 'Cyclone season exposure',
    detail:
      'IMD long-range outlook places two low-pressure systems over west Bay of Bengal in September. Coastal works exposed.',
    band: 'moderate',
    evidence: ['predicted'],
    detectedAt: '2026-08-20T09:00:00Z',
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export function getAlertsForProject(projectId: string): Alert[] {
  return alerts.filter((a) => a.projectId === projectId);
}
